//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace susheguanli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tushuguanliEntities : DbContext
    {
        public tushuguanliEntities()
            : base("name=tushuguanliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Book { get; set; }
        public DbSet<HuanShu> HuanShu { get; set; }
        public DbSet<JieShu> JieShu { get; set; }
        public DbSet<User> User { get; set; }
    }
}
